CREATE TABLE IF NOT EXISTS "order_items" (
  "id" SERIAL PRIMARY KEY,
  "orderId" INTEGER NOT NULL REFERENCES "orders" ("id") ON DELETE RESTRICT,
  "productId" INTEGER NOT NULL REFERENCES "products" ("id") ON DELETE RESTRICT,
  "quantity" INTEGER NOT NULL,
  "price" NUMERIC(10, 2) NOT NULL
);
